##------------------------------------------------------------------
##------DB CONFIGURATION----------------------------------------
##------------------------------------------------------------------
spring:
  data:
    mongodb:
      database: UsersDB
      uri: mongodb://sr-mongodb/${spring.data.mongodb.database}



##------------------------------------------------------------------
##------LOGGER CONFIGURATION----------------------------------------
##------------------------------------------------------------------
logging:
  file:
    name: logs/user.log
    max-size: 10MB
  level:
    com.mg: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot: DEBUG
    zipkin2.reporter.AsyncReporter: DEBUG


