##------------------------------------------------------------------
##------DB CONFIGURATION----------------------------------------
##------------------------------------------------------------------
spring:
  data:
    mongodb:
      uri: mongodb://localhost/smartrent2
      database: smartrent2



##------------------------------------------------------------------
##------LOGGER CONFIGURATION----------------------------------------
##------------------------------------------------------------------
logging:
  file:
    name: logs/user.log
    max-size: 10MB
  level:
    com.mg: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot: DEBUG
    zipkin2.reporter.AsyncReporter: DEBUG


