##------------------------------------------------------------------
##------SERVICE CONFIGURATION-----------------------------------
##------------------------------------------------------------------
server:
  port: 8080
spring:
  application:
    name: user-service
  data:
    mongodb:
      database: UsersDB
      uri: mongodb://localhost/${spring.data.mongodb.database}
##------------------------------------------------------------------
##------GATEWAY API CONFIGURATION-----------------------------------
##------------------------------------------------------------------
eureka:
  client:
    registerWithEureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:12341234@localhost:8081/eureka
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
##------------------------------------------------------------------
##------LOGGER CONFIGURATION----------------------------------------
##------------------------------------------------------------------
logging:
  file:
    name: logs/user.log
    max-size: 10MB
  level:
    com.mg: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot: INFO
    zipkin2.reporter.AsyncReporter: INFO